Repository deepakuniyaliit/hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#18 Upadte README.md
  README.md
Labels: documentation

#48 Update README.md
  README.md
  problem_list .pdf
  problem_list.txt
Labels: documentation

#68 weather app
  Android/WeatherApp_Sailesh_Kumar/.gitignore
  Android/WeatherApp_Sailesh_Kumar/.idea/.gitignore
  Android/WeatherApp_Sailesh_Kumar/.idea/.name
  Android/WeatherApp_Sailesh_Kumar/.idea/compiler.xml
  Android/WeatherApp_Sailesh_Kumar/.idea/gradle.xml
  Android/WeatherApp_Sailesh_Kumar/.idea/jarRepositories.xml
  Android/WeatherApp_Sailesh_Kumar/.idea/misc.xml
  Android/WeatherApp_Sailesh_Kumar/.idea/runConfigurations.xml
  Android/WeatherApp_Sailesh_Kumar/.idea/vcs.xml
  Android/WeatherApp_Sailesh_Kumar/.project
  Android/WeatherApp_Sailesh_Kumar/.settings/org.eclipse.buildship.core.prefs
  Android/WeatherApp_Sailesh_Kumar/README.md
  Android/WeatherApp_Sailesh_Kumar/app/.classpath
  Android/WeatherApp_Sailesh_Kumar/app/.gitignore
  Android/WeatherApp_Sailesh_Kumar/app/.project
  Android/WeatherApp_Sailesh_Kumar/app/.settings/org.eclipse.buildship.core.prefs
  Android/WeatherApp_Sailesh_Kumar/app/build.gradle
  Android/WeatherApp_Sailesh_Kumar/app/proguard-rules.pro
  Android/WeatherApp_Sailesh_Kumar/app/src/androidTest/java/com/example/weatherapp/ExampleInstrumentedTest.java
  Android/WeatherApp_Sailesh_Kumar/app/src/main/AndroidManifest.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/ic_launcher-playstore.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/java/com/example/weatherapp/MainActivity.java
  Android/WeatherApp_Sailesh_Kumar/app/src/main/java/com/example/weatherapp/ShowWeather.java
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/drawable/background.jpg
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/drawable/humidity.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/drawable/next.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/drawable/pressure.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/drawable/weather.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/drawable/wind.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/layout/activity_main.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/layout/activity_show_weather.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/values-night/themes.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/values/colors.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/values/ic_launcher_background.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/values/strings.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/main/res/values/themes.xml
  Android/WeatherApp_Sailesh_Kumar/app/src/test/java/com/example/weatherapp/ExampleUnitTest.java
  Android/WeatherApp_Sailesh_Kumar/build.gradle
  Android/WeatherApp_Sailesh_Kumar/gradle.properties
  Android/WeatherApp_Sailesh_Kumar/gradle/wrapper/gradle-wrapper.jar
  Android/WeatherApp_Sailesh_Kumar/gradle/wrapper/gradle-wrapper.properties
  Android/WeatherApp_Sailesh_Kumar/gradlew
  Android/WeatherApp_Sailesh_Kumar/gradlew.bat
  Android/WeatherApp_Sailesh_Kumar/images/dehradun.jpeg
  Android/WeatherApp_Sailesh_Kumar/images/home.jpeg
  Android/WeatherApp_Sailesh_Kumar/images/loading.jpeg
  Android/WeatherApp_Sailesh_Kumar/images/lucknow.jpeg
  Android/WeatherApp_Sailesh_Kumar/images/washingtonDC.jpeg
  Android/WeatherApp_Sailesh_Kumar/settings.gradle
Labels: hacktoberfest-accepted, Hacktoberfest

#77 Tic-tac-toe App
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/.gitignore
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/Image/snapshot.jpg
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/README.md
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/package-lock.json
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/package.json
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/public/index.html
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/public/styles.css
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/src/components/App.jsx
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/src/components/ListItem.jsx
  HTML CSS JavaScript/Tic-tac-toe_Naman_Vijay/src/index.js
Labels: hacktoberfest-accepted, Hacktoberfest

#64 Tamanna-S improved the road_cross game
  Python/road_cross improved by Tamanna-S/README.md
  Python/road_cross improved by Tamanna-S/car.py
  Python/road_cross improved by Tamanna-S/game_ss.png
  Python/road_cross improved by Tamanna-S/main.py
  Python/road_cross improved by Tamanna-S/player.py
  Python/road_cross improved by Tamanna-S/score.py
Labels: hacktoberfest-accepted, Hacktoberfest

#94 Improved UI of Movie-Website
  HTML CSS JavaScript/Movie-App_Nitin_Shaily/docs/index.html
  HTML CSS JavaScript/Movie-App_Nitin_Shaily/docs/style.css
Labels: hacktoberfest-accepted
